// Package domain holds the core types of the wallet service. It has no
// dependencies on transport, storage, or HTTP concerns.
package domain

import "time"

// Wallet is a stored-balance account.
type Wallet struct {
	ID        string
	Balance   int64 // minor units (e.g. cents); never negative
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// TransferStatus is the state of the transfer state machine.
type TransferStatus string

// Transfer is one attempted movement of funds between two wallets.
type Transfer struct {
	ID            string // UUID, generated by the database
	FromWalletID  string
	ToWalletID    string
	Amount        int64
	Status        TransferStatus
	FailureReason string // empty unless Status == TransferFailed
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// EntryType distinguishes the two sides of a double-entry pair.
type EntryType string

// LedgerEntry is one side of a transfer's double-entry pair. Entries are
// immutable: they are written once, inside the transfer's transaction.
type LedgerEntry struct {
	ID         int64
	TransferID string
	WalletID   string
	EntryType  EntryType
	Amount     int64
	CreatedAt  time.Time
}

// IdempotencyRecord is the persisted memory of one idempotency key.
//
// While the owning transaction is in flight the record is "claimed"
// (Status == nil). Once the transaction commits, the record is "complete" and
// later requests with the same key replay the stored outcome verbatim.
type IdempotencyRecord struct {
	Key string
	// RequestMatches reports whether the stored request body equals the
	// canonical request presented now (compared inside PostgreSQL as jsonb).
	RequestMatches bool
	// TransferID is set for outcomes that produced a transfer row (201, 422).
	TransferID *string
	// ResponseStatus is nil until the outcome has been recorded. Only 201,
	// 404, and 422 are ever recorded (see ErrKeyReused, ErrValidation, which
	// do not claim a key at all).
	ResponseStatus *int
	// ResponseBody is the exact response body stored for replay.
	ResponseBody []byte
}

// Complete reports whether the outcome has been recorded.
func (r IdempotencyRecord) Complete() bool { return r.ResponseStatus != nil }
